# evaluacion otros dias

# 01 de enero de 2023

In [5]:
import pandas as pd
import numpy as np

In [6]:
dataPrueba1 = pd.read_csv('01 de enero 2023.csv')

In [7]:
dataPrueba1.head()

,01/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,REAL,1149.850000,1069.360000,1005.650000,967.860000,942.660000,832.495500,810.763000,835.511000,882.730000,...,1063.859000,1067.552000,1060.451000,1064.566000,1156.810000,1322.060000,1315.190000,1261.360000,1187.200000,1098.040000
1,PROPHET_Domingo,1074.229469,1018.523656,980.973462,952.379697,939.963370,853.997129,838.984606,903.966111,975.402121,...,1097.568150,1109.388190,1114.653692,1124.058553,1229.144311,1396.649461,1386.367965,1326.101432,1223.969359,1124.038669
2,ARIMA_Domingo,1062.484207,1008.362265,969.143376,946.707704,899.670701,849.384674,824.628977,907.433009,963.801012,...,1058.470430,1044.433898,1053.986565,1074.324970,1168.393598,1315.625518,1313.380436,1264.071874,1138.046101,1048.721529
3,PROPHET_TodosDias,1089.683868,1086.939045,982.647621,953.654213,953.390684,843.173877,862.795408,916.909957,966.634127,...,1105.227662,1122.475727,1125.758877,1108.550855,1271.344942,1397.854078,1381.450979,1316.351968,1202.890701,1108.298561
4,ARIMA_TodosDias,1082.865457,1029.878105,992.768773,950.746046,959.644263,872.311654,919.117898,1031.723599,1135.113263,...,1344.021356,1349.952437,1307.556718,1274.881015,1352.337128,1518.808742,1499.539584,1425.553656,1324.294526,1214.961043

In [8]:
dataPrueba01 = dataPrueba1.set_index('01/01/2023')
dataPrueba01

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
01/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,1149.850000,1069.360000,1005.650000,967.860000,942.660000,832.495500,810.763000,835.511000,882.730000,941.549000,...,1063.859000,1067.552000,1060.451000,1064.566000,1156.810000,1322.060000,1315.190000,1261.360000,1187.200000,1098.040000
PROPHET_Domingo,1074.229469,1018.523656,980.973462,952.379697,939.963370,853.997129,838.984606,903.966111,975.402121,1024.239214,...,1097.568150,1109.388190,1114.653692,1124.058553,1229.144311,1396.649461,1386.367965,1326.101432,1223.969359,1124.038669
ARIMA_Domingo,1062.484207,1008.362265,969.143376,946.707704,899.670701,849.384674,824.628977,907.433009,963.801012,1007.289502,...,1058.470430,1044.433898,1053.986565,1074.324970,1168.393598,1315.625518,1313.380436,1264.071874,1138.046101,1048.721529
PROPHET_TodosDias,1089.683868,1086.939045,982.647621,953.654213,953.390684,843.173877,862.795408,916.909957,966.634127,1029.029949,...,1105.227662,1122.475727,1125.758877,1108.550855,1271.344942,1397.854078,1381.450979,1316.351968,1202.890701,1108.298561
ARIMA_TodosDias,1082.865457,1029.878105,992.768773,950.746046,959.644263,872.311654,919.117898,1031.723599,1135.113263,1203.322630,...,1344.021356,1349.952437,1307.556718,1274.881015,1352.337128,1518.808742,1499.539584,1425.553656,1324.294526,1214.961043
CNDC_Predic,1066.280000,971.660000,898.420000,854.860000,836.170000,730.190000,728.570000,768.750000,800.400000,853.640000,...,944.670000,959.690000,960.090000,967.450000,1056.100000,1251.730000,1251.570000,1193.530000,1097.650000,1002.370000

In [9]:
#dataPrueba_1 = dataPrueba01.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [10]:
# invertir columnas y filas
dataPrueba1inv = dataPrueba01.transpose()
dataPrueba1inv

01/01/2023,REAL,PROPHET_Domingo,ARIMA_Domingo,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,1149.8500,1074.229469,1062.484207,1089.683868,1082.865457,1066.28
H2,1069.3600,1018.523656,1008.362265,1086.939045,1029.878105,971.66
H3,1005.6500,980.973462,969.143376,982.647621,992.768773,898.42
H4,967.8600,952.379697,946.707704,953.654213,950.746046,854.86
H5,942.6600,939.963370,899.670701,953.390684,959.644263,836.17
H6,832.4955,853.997129,849.384674,843.173877,872.311654,730.19
H7,810.7630,838.984606,824.628977,862.795408,919.117898,728.57
H8,835.5110,903.966111,907.433009,916.909957,1031.723599,768.75
H9,882.7300,975.402121,963.801012,966.634127,1135.113263,800.40
H10,941.5490,1024.239214,1007.289502,1029.029949,1203.322630,853.64
H11,991.4760,1057.600092,1037.700951,1059.599520,1267.289508,894.94
H12,1020.3860,1081.933555,1021.571283,1077.528761,1283.709488,917.11
H13,1043.6120,1081.656140,1017.528351,1087.307696,1298.571577,930.28
H14,1051.7350,1083.757806,1054.718216,1095.612980,1327.124489,936.62
H15,1063.8590,1097.568150,1058.470430,1105.227662,1344.021356,944.67
H16,1067.5520,1109.388190,1044.433898,1122.475727,1349.952437,959.69
H17,1060.4510,1114.653692,1053.986565,1125.758877,1307.556718,960.09
H18,1064.5660,1124.058553,1074.324970,1108.550855,1274.881015,967.45
H19,1156.8100,1229.144311,1168.393598,1271.344942,1352.337128,1056.10
H20,1322.0600,1396.649461,1315.625518,1397.854078,1518.808742,1251.73
H21,1315.1900,1386.367965,1313.380436,1381.450979,1499.539584,1251.57
H22,1261.3600,1326.101432,1264.071874,1316.351968,1425.553656,1193.53
H23,1187.2000,1223.969359,1138.046101,1202.890701,1324.294526,1097.65
H24,1098.0400,1124.038669,1048.721529,1108.298561,1214.961043,1002.37

In [11]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico DOMINGO
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_Domingo']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_Domingo'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_Domingo']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_Domingo']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_Domingo']))

MSE of PROPHET_Lunes: 3025.3338359462746
RMSE of PROPHET_Lunes: 55.00303478851212
MAE of PROPHET_Lunest: 49.810058416666664
MAPE of PROPHET_Lunes: 0.04762088295446577
R2 of PROPHET_Lunes: 0.8377314202626379

In [12]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico DOMINGO
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_Domingo']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_Domingo'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_Domingo']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_Domingo']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_Domingo']))

MSE of ARIMA_Lunes: 1670.370479384259
RMSE of ARIMA_Lunes: 40.870166128659896
MAE of ARIMA_Lunes: 30.863311875000004
MAPE of ARIMA_Lunes: 0.03100991843921783
R2 of ARIMA_Lunes: 0.9104070294311435

In [13]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 3258.857901811992
RMSE of PROPHET_TodosDias: 57.0864073296962
MAE of PROPHET_TodosDias: 49.88063133333335
MAPE of PROPHET_TodosDias: 0.048104239171879344
R2 of PROPHET_TodosDias: 0.8252059865229687

In [14]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 37957.610747460254
RMSE of ARIMA_TodosDias: 194.82713041940605
MAE of ARIMA_TodosDias: 170.67877887499995
MAPE of ARIMA_TodosDias: 0.16395537087119275
R2 of ARIMA_TodosDias: -1.0359166691061952

In [15]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

#print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['CNDC_Predic']))

RMSE of PROPHET_Lunes: 95.88534297627078
MAE of PROPHET_Lunest: 94.58272916666664
MAPE of PROPHET_Lunes: 0.09215505438419956
R2 of PROPHET_Lunes: 0.5068652782270061

In [16]:
# exportar a csv
#dataPrueba1inv.to_csv('01enero2023.csv')# exportar a csv

# 02 de enero de 2023

In [17]:
dataPrueba2 = pd.read_csv('02 de enero 2023.csv')

In [18]:
dataPrueba2.head()

,02/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,1024.410000,963.780000,928.090000,899.610000,897.030000,830.520000,834.592000,886.622000,962.326000,...,1063.833000,1061.364000,1181.080000,1349.050000,1339.760000,1276.040000,1171.000000,1072.280000,25261.425,1352.47
1,PROPHET_Lunes,997.176982,938.587162,909.653092,893.344412,907.196613,874.351865,928.274322,1017.923628,1101.574226,...,1227.567391,1179.175837,1251.643379,1419.731253,1404.620503,1331.241682,1215.416369,1114.951718,NaN,NaN
2,ARIMA_Lunes,950.173923,892.783150,870.550458,878.907091,869.964752,857.498835,891.786794,951.692740,1065.104512,...,1236.301128,1239.804790,1344.449804,1472.556890,1426.698758,1349.892376,1230.888892,1122.487578,NaN,NaN
3,PROPHET_TodosDias,1038.044102,987.086101,955.129833,993.694556,950.309714,889.503413,1039.763979,1123.262883,1227.849998,...,1343.305665,1281.638086,1400.518944,1526.662107,1496.498742,1422.303833,1288.965107,1180.269068,NaN,NaN
4,ARIMA_TodosDias,1117.709462,1062.701392,1026.426255,1001.300208,1022.755655,955.967148,1067.498590,1206.993137,1343.962763,...,1480.583870,1413.328693,1461.463832,1607.402284,1572.298439,1487.090956,1373.069099,1261.894553,NaN,NaN

In [19]:
dataPrueba02 = dataPrueba2.set_index('02/01/2023')
dataPrueba02

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
02/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,1024.410000,963.780000,928.090000,899.610000,897.030000,830.520000,834.592000,886.622000,962.326000,1018.745000,...,1063.833000,1061.364000,1181.080000,1349.050000,1339.760000,1276.040000,1171.000000,1072.280000,25261.425,1352.47
PROPHET_Lunes,997.176982,938.587162,909.653092,893.344412,907.196613,874.351865,928.274322,1017.923628,1101.574226,1166.828666,...,1227.567391,1179.175837,1251.643379,1419.731253,1404.620503,1331.241682,1215.416369,1114.951718,NaN,NaN
ARIMA_Lunes,950.173923,892.783150,870.550458,878.907091,869.964752,857.498835,891.786794,951.692740,1065.104512,1136.751562,...,1236.301128,1239.804790,1344.449804,1472.556890,1426.698758,1349.892376,1230.888892,1122.487578,NaN,NaN
PROPHET_TodosDias,1038.044102,987.086101,955.129833,993.694556,950.309714,889.503413,1039.763979,1123.262883,1227.849998,1284.431629,...,1343.305665,1281.638086,1400.518944,1526.662107,1496.498742,1422.303833,1288.965107,1180.269068,NaN,NaN
ARIMA_TodosDias,1117.709462,1062.701392,1026.426255,1001.300208,1022.755655,955.967148,1067.498590,1206.993137,1343.962763,1419.953229,...,1480.583870,1413.328693,1461.463832,1607.402284,1572.298439,1487.090956,1373.069099,1261.894553,NaN,NaN
CNDC_Predic,959.640000,905.770000,870.630000,847.440000,843.140000,765.710000,784.740000,846.250000,908.450000,972.930000,...,1121.280000,1113.270000,1198.130000,1359.410000,1349.730000,1294.930000,1193.460000,1090.290000,NaN,NaN

In [20]:
dataPrueba_2 = dataPrueba02.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [21]:
# invertir columnas y filas
dataPrueba2inv = dataPrueba_2.transpose()
dataPrueba2inv

02/01/2023,REAL,PROPHET_Lunes,ARIMA_Lunes,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,1024.410,997.176982,950.173923,1038.044102,1117.709462,959.64
H2,963.780,938.587162,892.783150,987.086101,1062.701392,905.77
H3,928.090,909.653092,870.550458,955.129833,1026.426255,870.63
H4,899.610,893.344412,878.907091,993.694556,1001.300208,847.44
H5,897.030,907.196613,869.964752,950.309714,1022.755655,843.14
H6,830.520,874.351865,857.498835,889.503413,955.967148,765.71
H7,834.592,928.274322,891.786794,1039.763979,1067.498590,784.74
H8,886.622,1017.923628,951.692740,1123.262883,1206.993137,846.25
H9,962.326,1101.574226,1065.104512,1227.849998,1343.962763,908.45
H10,1018.745,1166.828666,1136.751562,1284.431629,1419.953229,972.93
H11,1066.459,1208.026364,1201.695345,1327.334454,1478.064733,1019.08
H12,1098.047,1213.052017,1228.105458,1351.475038,1492.922375,1049.55
H13,1095.101,1195.843630,1216.795598,1331.820722,1470.054299,1053.81
H14,1093.320,1231.153405,1270.723826,1365.983265,1523.430887,1078.70
H15,1071.572,1253.265851,1282.938190,1397.238091,1557.233759,1104.05
H16,1066.278,1247.975938,1284.360386,1400.194808,1543.300133,1123.61
H17,1063.833,1227.567391,1236.301128,1343.305665,1480.583870,1121.28
H18,1061.364,1179.175837,1239.804790,1281.638086,1413.328693,1113.27
H19,1181.080,1251.643379,1344.449804,1400.518944,1461.463832,1198.13
H20,1349.050,1419.731253,1472.556890,1526.662107,1607.402284,1359.41
H21,1339.760,1404.620503,1426.698758,1496.498742,1572.298439,1349.73
H22,1276.040,1331.241682,1349.892376,1422.303833,1487.090956,1294.93
H23,1171.000,1215.416369,1230.888892,1288.965107,1373.069099,1193.46
H24,1072.280,1114.951718,1122.487578,1180.269068,1261.894553,1090.29

In [22]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico LUNES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_Lunes']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_Lunes'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_Lunes']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_Lunes']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_Lunes']))

MSE of PROPHET_Lunes: 10886.176032535846
RMSE of PROPHET_Lunes: 104.33683928764493
MAE of PROPHET_Lunest: 88.8301670416667
MAPE of PROPHET_Lunes: 0.08483399690006367
R2 of PROPHET_Lunes: 0.43586902374493397

In [23]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico LUNES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['ARIMA_Lunes']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['ARIMA_Lunes'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba2inv['REAL'],dataPrueba2inv['ARIMA_Lunes']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba2inv['REAL'],dataPrueba2inv['ARIMA_Lunes']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba2inv['REAL'],dataPrueba2inv['ARIMA_Lunes']))

MSE of ARIMA_Lunes: 14338.213898368907
RMSE of ARIMA_Lunes: 119.74228116404376
MAE of ARIMA_Lunes: 105.12854533333335
MAPE of ARIMA_Lunes: 0.09831780779209269
R2 of ARIMA_Lunes: 0.25698146162012525

In [24]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba2inv['REAL'],dataPrueba2inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 42245.89632854361
RMSE of PROPHET_TodosDias: 205.53806540041094
MAE of PROPHET_TodosDias: 181.3489640833333
MAPE of PROPHET_TodosDias: 0.17207836886755182
R2 of PROPHET_TodosDias: -1.1892185710908532

In [25]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba1inv['REAL'],dataPrueba1inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 37957.610747460254
RMSE of ARIMA_TodosDias: 194.82713041940605
MAE of ARIMA_TodosDias: 170.67877887499995
MAPE of ARIMA_TodosDias: 0.16395537087119275
R2 of ARIMA_TodosDias: -1.0359166691061952

In [26]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba2inv['REAL'],dataPrueba2inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba2inv['REAL'],dataPrueba2inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba2inv['REAL'],dataPrueba2inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba2inv['REAL'],dataPrueba2inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 2014.1485613750003
RMSE of PROPHET_Lunes: 44.87926649773813
MAE of PROPHET_Lunest: 41.19645833333335
MAPE of PROPHET_Lunes: 0.041443557795505376
R2 of PROPHET_Lunes: 0.8956250945368429

In [27]:
# exportar a csv
#dataPrueba2inv.to_csv('02enero2023.csv')# exportar a csv

# 03 de enero de 2023

In [28]:
dataPrueba3 = pd.read_csv('03 de enero 2023.csv')

In [29]:
dataPrueba3.head()

,03/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,992.610000,944.100000,914.650000,898.280000,909.250000,907.912000,967.444000,1072.211000,1190.475000,...,1272.207000,1232.710000,1308.250000,1472.250000,1450.580000,1362.820000,1220.690000,1097.720000,28142.768,1473.83
1,PROPHET_Martes,1038.626626,979.494143,954.728689,934.640699,951.741270,917.474018,970.728654,1062.711611,1162.392002,...,1238.588208,1201.905936,1271.525075,1448.307681,1420.301373,1362.975314,1235.839710,1142.836071,NaN,NaN
2,ARIMA_Martes,1070.246439,1004.591529,958.441393,953.579722,989.764026,966.802029,1042.367281,1181.802187,1272.443513,...,1443.842190,1406.742461,1464.731364,1590.287799,1527.560685,1440.635958,1315.722303,1214.191995,NaN,NaN
3,PROPHET_TodosDias,1101.574343,1051.444358,1017.292960,1057.643844,1016.236763,1016.236763,1073.782369,1070.901630,1273.444872,...,1407.975949,1298.454382,1298.454382,1540.613273,1540.613273,1427.278965,1300.075112,1200.128008,NaN,NaN
4,ARIMA_TodosDias,1170.989628,1111.134719,1060.514945,1039.311261,1052.034142,982.112307,1063.139114,1202.833462,1315.790047,...,1449.653123,1381.552916,1442.925928,1585.713712,1558.368991,1474.181939,1355.399547,1242.685378,NaN,NaN

In [30]:
dataPrueba03 = dataPrueba3.set_index('03/01/2023')
dataPrueba03

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
03/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,992.610000,944.100000,914.650000,898.280000,909.250000,907.912000,967.444000,1072.211000,1190.475000,1228.305000,...,1272.207000,1232.710000,1308.250000,1472.250000,1450.580000,1362.820000,1220.690000,1097.720000,28142.768,1473.83
PROPHET_Martes,1038.626626,979.494143,954.728689,934.640699,951.741270,917.474018,970.728654,1062.711611,1162.392002,1223.746305,...,1238.588208,1201.905936,1271.525075,1448.307681,1420.301373,1362.975314,1235.839710,1142.836071,NaN,NaN
ARIMA_Martes,1070.246439,1004.591529,958.441393,953.579722,989.764026,966.802029,1042.367281,1181.802187,1272.443513,1340.748576,...,1443.842190,1406.742461,1464.731364,1590.287799,1527.560685,1440.635958,1315.722303,1214.191995,NaN,NaN
PROPHET_TodosDias,1101.574343,1051.444358,1017.292960,1057.643844,1016.236763,1016.236763,1073.782369,1070.901630,1273.444872,1317.823095,...,1407.975949,1298.454382,1298.454382,1540.613273,1540.613273,1427.278965,1300.075112,1200.128008,NaN,NaN
ARIMA_TodosDias,1170.989628,1111.134719,1060.514945,1039.311261,1052.034142,982.112307,1063.139114,1202.833462,1315.790047,1390.549533,...,1449.653123,1381.552916,1442.925928,1585.713712,1558.368991,1474.181939,1355.399547,1242.685378,NaN,NaN
CNDC_Predic,980.670000,922.520000,891.411000,871.780000,891.460000,864.710000,973.160000,1089.640000,1231.900000,1298.490000,...,1388.380000,1311.910000,1360.780000,1502.650000,1477.650000,1409.330000,1296.500000,1173.970000,NaN,NaN

In [31]:
dataPrueba_3 = dataPrueba03.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [32]:
# invertir columnas y filas
dataPrueba3inv = dataPrueba_3.transpose()
dataPrueba3inv

03/01/2023,REAL,PROPHET_Martes,ARIMA_Martes,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,992.610,1038.626626,1070.246439,1101.574343,1170.989628,980.670
H2,944.100,979.494143,1004.591529,1051.444358,1111.134719,922.520
H3,914.650,954.728689,958.441393,1017.292960,1060.514945,891.411
H4,898.280,934.640699,953.579722,1057.643844,1039.311261,871.780
H5,909.250,951.741270,989.764026,1016.236763,1052.034142,891.460
H6,907.912,917.474018,966.802029,1016.236763,982.112307,864.710
H7,967.444,970.728654,1042.367281,1073.782369,1063.139114,973.160
H8,1072.211,1062.711611,1181.802187,1070.901630,1202.833462,1089.640
H9,1190.475,1162.392002,1272.443513,1273.444872,1315.790047,1231.900
H10,1228.305,1223.746305,1340.748576,1317.823095,1390.549533,1298.490
H11,1285.255,1276.866840,1397.135987,1361.306743,1429.599430,1352.620
H12,1271.919,1279.715879,1420.183305,1372.119606,1439.406539,1364.760
H13,1253.662,1256.410301,1401.156017,1348.537744,1421.976983,1361.380
H14,1281.690,1281.381219,1471.097708,1395.059280,1477.383794,1425.766
H15,1307.170,1274.465774,1509.478642,1414.012768,1508.401851,1453.080
H16,1318.856,1279.111390,1490.032240,1407.975949,1503.974953,1441.720
H17,1272.207,1238.588208,1443.842190,1407.975949,1449.653123,1388.380
H18,1232.710,1201.905936,1406.742461,1298.454382,1381.552916,1311.910
H19,1308.250,1271.525075,1464.731364,1298.454382,1442.925928,1360.780
H20,1472.250,1448.307681,1590.287799,1540.613273,1585.713712,1502.650
H21,1450.580,1420.301373,1527.560685,1540.613273,1558.368991,1477.650
H22,1362.820,1362.975314,1440.635958,1427.278965,1474.181939,1409.330
H23,1220.690,1235.839710,1315.722303,1300.075112,1355.399547,1296.500
H24,1097.720,1142.836071,1214.191995,1200.128008,1242.685378,1173.970

In [33]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico MARTES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_Martes']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_Martes'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_Martes']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_Martes']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_Martes']))

MSE of PROPHET_Lunes: 794.8726551203553
RMSE of PROPHET_Lunes: 28.19348604057957
MAE of PROPHET_Lunest: 23.450415000000007
MAPE of PROPHET_Lunes: 0.021060702210288964
R2 of PROPHET_Lunes: 0.9743938909409983

In [34]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico MARTES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_Martes']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_Martes'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_Martes']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_Martes']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_Martes']))

MSE of ARIMA_Lunes: 14862.585703271056
RMSE of ARIMA_Lunes: 121.91220489873463
MAE of ARIMA_Lunes: 113.02372287499998
MAPE of ARIMA_Lunes: 0.09453329935842993
R2 of ARIMA_Lunes: 0.5212151431236567

In [35]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba3inv['REAL'],dataPrueba3inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 9263.627669532723
RMSE of PROPHET_TodosDias: 96.2477411139229
MAE of PROPHET_TodosDias: 90.42418362499996
MAPE of PROPHET_TodosDias: 0.08070221673772343
R2 of PROPHET_TodosDias: 0.7015805502176642

In [36]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba3inv['REAL'],dataPrueba3inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 22214.059018466014
RMSE of ARIMA_TodosDias: 149.0438157672636
MAE of ARIMA_TodosDias: 145.77576008333332
MAPE of ARIMA_TodosDias: 0.1264115735872086
R2 of ARIMA_TodosDias: 0.2843940294010815

In [37]:
# Evaluacion de la prediccion de CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba3inv['REAL'],dataPrueba3inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba3inv['REAL'],dataPrueba3inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba3inv['REAL'],dataPrueba3inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba3inv['REAL'],dataPrueba3inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 5451.052600124998
RMSE of PROPHET_Lunes: 73.83124406458961
MAE of PROPHET_Lunest: 60.98845833333334
MAPE of PROPHET_Lunes: 0.050012055495134496
R2 of PROPHET_Lunes: 0.8243992336809962

In [38]:
# exportar a csv
#dataPrueba3inv.to_csv('03enero2023.csv')# exportar a csv

# 04 de enero de 2023

In [39]:
dataPrueba4 = pd.read_csv('04 de enero 2023.csv')

In [40]:
dataPrueba4.head()

,04/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,1014.670000,977.700000,951.170000,937.720000,962.600000,947.820000,998.107000,1109.557000,1186.861000,...,1230.696000,1186.831000,1260.910000,1412.940000,1384.460000,1291.680000,1154.500000,1051.910000,27781.967,1418.95
1,PROPHET_Miercoles,1066.740201,1009.452528,977.841444,962.316112,967.835114,922.627224,968.211448,1071.429607,1170.087368,...,1266.361581,1218.128076,1283.884539,1456.058378,1428.106279,1346.864200,1226.725849,1134.871746,NaN,NaN
2,ARIMA_Miercoles,1120.626695,1063.410602,1027.638053,1009.899355,1025.345110,1013.865939,1088.536653,1188.081873,1309.354357,...,1433.854066,1319.498417,1465.989318,1578.639653,1526.149913,1465.259307,1311.472490,1208.100638,NaN,NaN
3,PROPHET_TodosDias,1110.987567,1122.397271,1028.537505,1067.061558,1026.497862,965.336075,1099.542271,1100.325981,1266.529519,...,1397.786412,1314.739146,1434.873827,1549.650441,1523.202669,1435.504571,1304.595994,1210.898684,NaN,NaN
4,ARIMA_TodosDias,1151.654154,1092.155099,1042.927787,1022.363163,1036.013729,979.858319,1070.796814,1215.003628,1351.511105,...,1438.013655,1367.015099,1439.812923,1577.058098,1545.991455,1463.640029,1347.046108,1241.049823,NaN,NaN

In [41]:
dataPrueba04 = dataPrueba4.set_index('04/01/2023')
dataPrueba04

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
04/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,1014.670000,977.700000,951.170000,937.720000,962.600000,947.820000,998.107000,1109.557000,1186.861000,1234.751000,...,1230.696000,1186.831000,1260.910000,1412.940000,1384.460000,1291.680000,1154.500000,1051.910000,27781.967,1418.95
PROPHET_Miercoles,1066.740201,1009.452528,977.841444,962.316112,967.835114,922.627224,968.211448,1071.429607,1170.087368,1238.031956,...,1266.361581,1218.128076,1283.884539,1456.058378,1428.106279,1346.864200,1226.725849,1134.871746,NaN,NaN
ARIMA_Miercoles,1120.626695,1063.410602,1027.638053,1009.899355,1025.345110,1013.865939,1088.536653,1188.081873,1309.354357,1383.549629,...,1433.854066,1319.498417,1465.989318,1578.639653,1526.149913,1465.259307,1311.472490,1208.100638,NaN,NaN
PROPHET_TodosDias,1110.987567,1122.397271,1028.537505,1067.061558,1026.497862,965.336075,1099.542271,1100.325981,1266.529519,1344.448361,...,1397.786412,1314.739146,1434.873827,1549.650441,1523.202669,1435.504571,1304.595994,1210.898684,NaN,NaN
ARIMA_TodosDias,1151.654154,1092.155099,1042.927787,1022.363163,1036.013729,979.858319,1070.796814,1215.003628,1351.511105,1417.480182,...,1438.013655,1367.015099,1439.812923,1577.058098,1545.991455,1463.640029,1347.046108,1241.049823,NaN,NaN
CNDC_Predic,1043.210000,999.930000,967.860000,934.580000,953.080000,925.730000,1030.940000,1104.700000,1224.420000,1279.610000,...,1334.500000,1255.860000,1344.350000,1442.850000,1410.840000,1337.610000,1221.230000,1126.540000,NaN,NaN

In [42]:
dataPrueba_4 = dataPrueba04.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [43]:
# invertir columnas y filas
dataPrueba4inv = dataPrueba_4.transpose()
dataPrueba4inv

04/01/2023,REAL,PROPHET_Miercoles,ARIMA_Miercoles,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,1014.670,1066.740201,1120.626695,1110.987567,1151.654154,1043.21
H2,977.700,1009.452528,1063.410602,1122.397271,1092.155099,999.93
H3,951.170,977.841444,1027.638053,1028.537505,1042.927787,967.86
H4,937.720,962.316112,1009.899355,1067.061558,1022.363163,934.58
H5,962.600,967.835114,1025.345110,1026.497862,1036.013729,953.08
H6,947.820,922.627224,1013.865939,965.336075,979.858319,925.73
H7,998.107,968.211448,1088.536653,1099.542271,1070.796814,1030.94
H8,1109.557,1071.429607,1188.081873,1100.325981,1215.003628,1104.70
H9,1186.861,1170.087368,1309.354357,1266.529519,1351.511105,1224.42
H10,1234.751,1238.031956,1383.549629,1344.448361,1417.480182,1279.61
H11,1253.756,1275.666346,1416.187287,1385.369002,1463.342131,1320.73
H12,1236.353,1271.823762,1400.771478,1393.674697,1465.543361,1321.28
H13,1216.144,1244.780813,1408.993692,1372.653015,1448.364317,1301.08
H14,1237.568,1289.307156,1472.092429,1421.621726,1500.545866,1362.34
H15,1254.230,1311.223191,1501.464466,1448.971644,1517.120296,1391.82
H16,1235.847,1312.989402,1489.052765,1436.344319,1496.024862,1386.98
H17,1230.696,1266.361581,1433.854066,1397.786412,1438.013655,1334.50
H18,1186.831,1218.128076,1319.498417,1314.739146,1367.015099,1255.86
H19,1260.910,1283.884539,1465.989318,1434.873827,1439.812923,1344.35
H20,1412.940,1456.058378,1578.639653,1549.650441,1577.058098,1442.85
H21,1384.460,1428.106279,1526.149913,1523.202669,1545.991455,1410.84
H22,1291.680,1346.864200,1465.259307,1435.504571,1463.640029,1337.61
H23,1154.500,1226.725849,1311.472490,1304.595994,1347.046108,1221.23
H24,1051.910,1134.871746,1208.100638,1210.898684,1241.049823,1126.54

In [44]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico MIERCOLES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_Miercoles']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_Miercoles'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_Miercoles']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_Miercoles']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_Miercoles']))

MSE of PROPHET_Lunes: 1852.5004056815076
RMSE of PROPHET_Lunes: 43.040683146082934
MAE of PROPHET_Lunest: 38.02341774999999
MAPE of PROPHET_Lunes: 0.03293055767363021
R2 of PROPHET_Lunes: 0.9041072594707853

In [45]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico MIERCOLES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_Miercoles']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_Miercoles'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_Miercoles']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_Miercoles']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_Miercoles']))

MSE of ARIMA_Lunes: 24495.67664261368
RMSE of ARIMA_Lunes: 156.5109473570896
MAE of ARIMA_Lunes: 145.79388270833329
MAPE of ARIMA_Lunes: 0.1233328218086091
R2 of ARIMA_Lunes: -0.26799300943394555

In [46]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba4inv['REAL'],dataPrueba4inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 18567.272169362328
RMSE of PROPHET_TodosDias: 136.26177809408745
MAE of PROPHET_TodosDias: 127.13463145833332
MAPE of PROPHET_TodosDias: 0.1087952726347788
R2 of PROPHET_TodosDias: 0.03888463019420274

In [47]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba4inv['REAL'],dataPrueba4inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 31250.313297741068
RMSE of ARIMA_TodosDias: 176.77758143424484
MAE of ARIMA_TodosDias: 165.064625125
MAPE of ARIMA_TodosDias: 0.1397610821799619
R2 of ARIMA_TodosDias: -0.6176396913740592

In [48]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba4inv['REAL'],dataPrueba4inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba4inv['REAL'],dataPrueba4inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba4inv['REAL'],dataPrueba4inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba4inv['REAL'],dataPrueba4inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 4965.746555458329
RMSE of PROPHET_Lunes: 70.46805343883375
MAE of PROPHET_Lunest: 57.18762499999996
MAPE of PROPHET_Lunes: 0.04784076291812394
R2 of PROPHET_Lunes: 0.7429533378152064

In [49]:
# exportar a csv
#dataPrueba4inv.to_csv('04enero2023.csv')# exportar a csv

# 05 de enero de 2023

In [50]:
dataPrueba5 = pd.read_csv('05 de enero 2023.csv')

In [51]:
dataPrueba5.head()

,05/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,974.350000,933.610000,912.770000,903.630000,929.080000,897.525000,990.292000,1087.694000,1224.261000,...,1383.041000,1320.303000,1351.930000,1523.600000,1489.960000,1408.930000,1266.460000,1141.460000,29285.061,1525.22
1,PROPHET_Jueves,1047.397104,1005.191324,972.517721,958.230800,974.412502,947.170339,1009.154936,1119.781537,1238.242449,...,1280.875549,1229.470942,1304.249124,1470.978669,1453.769834,1361.737692,1240.064762,1141.846995,NaN,NaN
2,ARIMA_Jueves,1113.093720,1054.291109,1041.356821,1002.787579,1013.344146,979.535478,1076.620502,1195.864925,1321.845552,...,1391.344984,1351.289771,1422.723537,1538.002034,1519.987801,1412.689948,1304.651271,1189.817722,NaN,NaN
3,PROPHET_TodosDias,1122.397271,1070.075215,1036.282511,1073.438933,1032.960809,969.378391,1095.275319,1095.494401,1290.719665,...,1373.181129,1297.997565,1422.465202,1537.106916,1515.637298,1425.757837,1313.026074,1195.852305,NaN,NaN
4,ARIMA_TodosDias,1141.278984,1081.506002,1041.372355,1028.242587,1046.306983,990.935965,1066.857519,1212.987487,1354.174357,...,1452.291311,1382.943066,1445.195501,1590.569286,1555.782725,1480.814792,1365.873348,1255.274111,NaN,NaN

In [52]:
dataPrueba05 = dataPrueba5.set_index('05/01/2023')
dataPrueba05

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
05/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,974.350000,933.610000,912.770000,903.630000,929.080000,897.525000,990.292000,1087.694000,1224.261000,1292.559000,...,1383.041000,1320.303000,1351.930000,1523.600000,1489.960000,1408.930000,1266.460000,1141.460000,29285.061,1525.22
PROPHET_Jueves,1047.397104,1005.191324,972.517721,958.230800,974.412502,947.170339,1009.154936,1119.781537,1238.242449,1292.011882,...,1280.875549,1229.470942,1304.249124,1470.978669,1453.769834,1361.737692,1240.064762,1141.846995,NaN,NaN
ARIMA_Jueves,1113.093720,1054.291109,1041.356821,1002.787579,1013.344146,979.535478,1076.620502,1195.864925,1321.845552,1350.426093,...,1391.344984,1351.289771,1422.723537,1538.002034,1519.987801,1412.689948,1304.651271,1189.817722,NaN,NaN
PROPHET_TodosDias,1122.397271,1070.075215,1036.282511,1073.438933,1032.960809,969.378391,1095.275319,1095.494401,1290.719665,1345.377781,...,1373.181129,1297.997565,1422.465202,1537.106916,1515.637298,1425.757837,1313.026074,1195.852305,NaN,NaN
ARIMA_TodosDias,1141.278984,1081.506002,1041.372355,1028.242587,1046.306983,990.935965,1066.857519,1212.987487,1354.174357,1415.184393,...,1452.291311,1382.943066,1445.195501,1590.569286,1555.782725,1480.814792,1365.873348,1255.274111,NaN,NaN
CNDC_Predic,1028.900000,973.470000,938.040000,915.870000,923.160000,938.890000,1040.260000,1151.150000,1243.450000,1394.140000,...,1335.280000,1208.150000,1327.400000,1467.550000,1434.340000,1336.480000,1214.760000,1003.180000,NaN,NaN

In [53]:
dataPrueba_5 = dataPrueba05.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [54]:
# invertir columnas y filas
dataPrueba5inv = dataPrueba_5.transpose()
dataPrueba5inv

05/01/2023,REAL,PROPHET_Jueves,ARIMA_Jueves,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,974.350,1047.397104,1113.093720,1122.397271,1141.278984,1028.90
H2,933.610,1005.191324,1054.291109,1070.075215,1081.506002,973.47
H3,912.770,972.517721,1041.356821,1036.282511,1041.372355,938.04
H4,903.630,958.230800,1002.787579,1073.438933,1028.242587,915.87
H5,929.080,974.412502,1013.344146,1032.960809,1046.306983,923.16
H6,897.525,947.170339,979.535478,969.378391,990.935965,938.89
H7,990.292,1009.154936,1076.620502,1095.275319,1066.857519,1040.26
H8,1087.694,1119.781537,1195.864925,1095.494401,1212.987487,1151.15
H9,1224.261,1238.242449,1321.845552,1290.719665,1354.174357,1243.45
H10,1292.559,1292.011882,1350.426093,1345.377781,1415.184393,1394.14
H11,1320.306,1322.658758,1407.945215,1373.585178,1466.141374,1340.39
H12,1355.509,1312.955930,1393.948493,1393.674697,1461.419365,1244.37
H13,1329.603,1282.172848,1400.693182,1361.699249,1450.906639,1341.66
H14,1392.276,1326.426330,1459.796890,1414.350538,1499.422637,1420.57
H15,1447.467,1327.635574,1494.122601,1426.916868,1519.879664,1482.66
H16,1416.554,1316.676412,1472.167009,1417.737472,1505.779184,1412.52
H17,1383.041,1280.875549,1391.344984,1373.181129,1452.291311,1335.28
H18,1320.303,1229.470942,1351.289771,1297.997565,1382.943066,1208.15
H19,1351.930,1304.249124,1422.723537,1422.465202,1445.195501,1327.40
H20,1523.600,1470.978669,1538.002034,1537.106916,1590.569286,1467.55
H21,1489.960,1453.769834,1519.987801,1515.637298,1555.782725,1434.34
H22,1408.930,1361.737692,1412.689948,1425.757837,1480.814792,1336.48
H23,1266.460,1240.064762,1304.651271,1313.026074,1365.873348,1214.76
H24,1141.460,1141.846995,1189.817722,1195.852305,1255.274111,1003.18

In [55]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico JUEVES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_Jueves']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_Jueves'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_Jueves']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_Jueves']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_Jueves']))

MSE of PROPHET_Lunes: 3492.2213635905887
RMSE of PROPHET_Lunes: 59.09501978670105
MAE of PROPHET_Lunest: 50.03303820833337
MAPE of PROPHET_Lunes: 0.04178739576973169
R2 of PROPHET_Lunes: 0.9182011031037017

In [56]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico JUEVES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_Jueves']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_Jueves'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_Jueves']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_Jueves']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_Jueves']))

MSE of ARIMA_Lunes: 5876.391932955726
RMSE of ARIMA_Lunes: 76.65762801545405
MAE of ARIMA_Lunes: 67.29901595833333
MAPE of ARIMA_Lunes: 0.061261079597804045
R2 of ARIMA_Lunes: 0.8623562690333403

In [57]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba5inv['REAL'],dataPrueba5inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 5705.5205850194225
RMSE of PROPHET_TodosDias: 75.53489647189187
MAE of PROPHET_TodosDias: 58.860395833333335
MAPE of PROPHET_TodosDias: 0.05598940359428339
R2 of PROPHET_TodosDias: 0.8663586177727691

In [58]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba5inv['REAL'],dataPrueba5inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 11828.019154414453
RMSE of ARIMA_TodosDias: 108.7566970554662
MAE of ARIMA_TodosDias: 104.9154014583333
MAPE of ARIMA_TodosDias: 0.09108050153763088
R2 of ARIMA_TodosDias: 0.7229502890662642

In [59]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba5inv['REAL'],dataPrueba5inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba5inv['REAL'],dataPrueba5inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba5inv['REAL'],dataPrueba5inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba5inv['REAL'],dataPrueba5inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 3666.8732568333385
RMSE of PROPHET_Lunes: 60.554712920080284
MAE of PROPHET_Lunest: 49.281000000000034
MAPE of PROPHET_Lunes: 0.04059637719275879
R2 of PROPHET_Lunes: 0.9141102020064648

In [60]:
# exportar a csv
#dataPrueba5inv.to_csv('05enero2023.csv')# exportar a csv

# 06 de enero de 2023

In [61]:
dataPrueba6 = pd.read_csv('06 de enero 2023.csv')

In [62]:
dataPrueba6.head()

,06/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,1057.490000,998.010000,971.910000,957.730000,979.340000,953.640000,1042.190000,1163.468000,1291.834000,...,1450.128000,1362.918000,1394.040000,1550.370000,1520.990000,1450.950000,1329.870000,1226.910000,30837.557,1551.9
1,PROPHET_Viernes,1056.698732,1003.761491,971.888454,957.908173,971.369534,924.885114,964.042106,1058.176910,1164.167063,...,1244.071509,1198.106675,1281.810730,1449.771581,1413.430023,1446.179367,1415.071659,1139.491327,NaN,NaN
2,ARIMA_Viernes,1113.093720,1054.291109,1041.356821,1002.787579,1013.344146,979.535478,1076.620502,1195.864925,1321.845552,...,1361.791380,1282.463417,1410.407502,1548.535802,1523.835140,1460.132573,1352.229594,1233.953579,NaN,NaN
3,PROPHET_TodosDias,1119.190596,1065.953175,1032.091426,1071.128240,1026.392778,965.386661,1093.984756,1090.989755,1279.961566,...,1356.422417,1295.728398,1416.792662,1516.748670,1487.557116,1414.807998,1308.760997,1201.095662,NaN,NaN
4,ARIMA_TodosDias,1164.305580,1100.548401,1060.103384,1036.958139,1042.673009,957.337035,1024.389117,1141.209023,1254.484041,...,1307.823390,1274.650893,1363.963222,1517.076893,1481.495730,1414.772726,1318.049138,1207.902882,NaN,NaN

In [63]:
dataPrueba06 = dataPrueba6.set_index('06/01/2023')
dataPrueba06

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
06/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,1057.490000,998.010000,971.910000,957.730000,979.340000,953.640000,1042.190000,1163.468000,1291.834000,1365.882000,...,1450.128000,1362.918000,1394.040000,1550.370000,1520.990000,1450.950000,1329.870000,1226.910000,30837.557,1551.9
PROPHET_Viernes,1056.698732,1003.761491,971.888454,957.908173,971.369534,924.885114,964.042106,1058.176910,1164.167063,1224.993562,...,1244.071509,1198.106675,1281.810730,1449.771581,1413.430023,1446.179367,1415.071659,1139.491327,NaN,NaN
ARIMA_Viernes,1113.093720,1054.291109,1041.356821,1002.787579,1013.344146,979.535478,1076.620502,1195.864925,1321.845552,1350.426093,...,1361.791380,1282.463417,1410.407502,1548.535802,1523.835140,1460.132573,1352.229594,1233.953579,NaN,NaN
PROPHET_TodosDias,1119.190596,1065.953175,1032.091426,1071.128240,1026.392778,965.386661,1093.984756,1090.989755,1279.961566,1332.813342,...,1356.422417,1295.728398,1416.792662,1516.748670,1487.557116,1414.807998,1308.760997,1201.095662,NaN,NaN
ARIMA_TodosDias,1164.305580,1100.548401,1060.103384,1036.958139,1042.673009,957.337035,1024.389117,1141.209023,1254.484041,1311.412514,...,1307.823390,1274.650893,1363.963222,1517.076893,1481.495730,1414.772726,1318.049138,1207.902882,NaN,NaN
CNDC_Predic,1041.630000,991.230000,958.530000,937.360000,956.080000,955.560000,1056.050000,1160.330000,1281.200000,1341.660000,...,1401.230000,1319.180000,1301.650000,1501.800000,1463.290000,1309.140000,1281.610000,1179.780000,NaN,NaN

In [64]:
dataPrueba_6 = dataPrueba06.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [65]:
# invertir columnas y filas
dataPrueba6inv = dataPrueba_6.transpose()
dataPrueba6inv

06/01/2023,REAL,PROPHET_Viernes,ARIMA_Viernes,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,1057.490,1056.698732,1113.093720,1119.190596,1164.305580,1041.63
H2,998.010,1003.761491,1054.291109,1065.953175,1100.548401,991.23
H3,971.910,971.888454,1041.356821,1032.091426,1060.103384,958.53
H4,957.730,957.908173,1002.787579,1071.128240,1036.958139,937.36
H5,979.340,971.369534,1013.344146,1026.392778,1042.673009,956.08
H6,953.640,924.885114,979.535478,965.386661,957.337035,955.56
H7,1042.190,964.042106,1076.620502,1093.984756,1024.389117,1056.05
H8,1163.468,1058.176910,1195.864925,1090.989755,1141.209023,1160.33
H9,1291.834,1164.167063,1321.845552,1279.961566,1254.484041,1281.20
H10,1365.882,1224.993562,1350.426093,1332.813342,1311.412514,1341.66
H11,1400.245,1249.802425,1407.945215,1371.765048,1359.879446,1338.92
H12,1424.374,1262.968955,1412.792214,1368.183005,1364.154995,1390.76
H13,1419.579,1233.046827,1397.418682,1350.471208,1337.595024,1318.89
H14,1487.611,1263.451784,1462.512054,1394.641576,1344.504186,1442.33
H15,1522.092,1283.869068,1481.410473,1419.248578,1356.508744,1468.04
H16,1502.504,1286.503830,1410.869448,1403.596461,1340.490590,1456.34
H17,1450.128,1244.071509,1361.791380,1356.422417,1307.823390,1401.23
H18,1362.918,1198.106675,1282.463417,1295.728398,1274.650893,1319.18
H19,1394.040,1281.810730,1410.407502,1416.792662,1363.963222,1301.65
H20,1550.370,1449.771581,1548.535802,1516.748670,1517.076893,1501.80
H21,1520.990,1413.430023,1523.835140,1487.557116,1481.495730,1463.29
H22,1450.950,1446.179367,1460.132573,1414.807998,1414.772726,1309.14
H23,1329.870,1415.071659,1352.229594,1308.760997,1318.049138,1281.61
H24,1226.910,1139.491327,1233.953579,1201.095662,1207.902882,1179.78

In [66]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico VIERNES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_Viernes']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_Viernes'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_Viernes']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_Viernes']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_Viernes']))

MSE of PROPHET_Lunes: 17092.87386795227
RMSE of PROPHET_Lunes: 130.73971802001208
MAE of PROPHET_Lunest: 105.86961445833333
MAPE of PROPHET_Lunes: 0.07638814699926129
R2 of PROPHET_Lunes: 0.5987765023181084

In [67]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico VIERNES
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_Viernes']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_Viernes'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_Viernes']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_Viernes']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_Viernes']))

MSE of ARIMA_Lunes: 1869.5717016778492
RMSE of ARIMA_Lunes: 43.238544166956515
MAE of ARIMA_Lunes: 34.411036333333335
MAPE of ARIMA_Lunes: 0.028426364345190247
R2 of ARIMA_Lunes: 0.956115273352559

In [68]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba6inv['REAL'],dataPrueba6inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 3860.53626925438
RMSE of PROPHET_TodosDias: 62.13321389767618
MAE of PROPHET_TodosDias: 54.729312375000006
MAPE of PROPHET_TodosDias: 0.04385816046135745
R2 of PROPHET_TodosDias: 0.9093810744264501

In [69]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba6inv['REAL'],dataPrueba6inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 6863.541710470015
RMSE of ARIMA_TodosDias: 82.84649485928789
MAE of ARIMA_TodosDias: 67.89158308333333
MAPE of ARIMA_TodosDias: 0.0530693725403506
R2 of ARIMA_TodosDias: 0.8388910938655256

In [70]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba6inv['REAL'],dataPrueba6inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba6inv['REAL'],dataPrueba6inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba6inv['REAL'],dataPrueba6inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba6inv['REAL'],dataPrueba6inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 2819.1069056249967
RMSE of PROPHET_Lunes: 53.09526255349903
MAE of PROPHET_Lunest: 41.79354166666665
MAPE of PROPHET_Lunes: 0.030555840510853267
R2 of PROPHET_Lunes: 0.9338266963325144

In [71]:
# exportar a csv
#dataPrueba6inv.to_csv('06enero2023.csv')# exportar a csv

# 07 de enero de 2023

In [72]:
dataPrueba7 = pd.read_csv('07 de enero 2023.csv')

In [73]:
dataPrueba7.head()

,07/01/2023,H1,H2,H3,H4,H5,H6,H7,H8,H9,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
0,REAL,1136.550000,1072.030000,1039.660000,1010.900000,1018.060000,972.210000,997.739000,1112.479000,1223.756000,...,1356.196000,1310.500000,1370.640000,1538.830000,1512.520000,1439.130000,1339.060000,1237.660000,30372.425,1540.81
1,PROPHET_Sabado,1058.211448,1000.510423,969.078795,950.777033,950.944046,885.658921,884.129930,975.253526,1063.502467,...,1114.109638,1109.464384,1191.743950,1375.092657,1343.384535,1272.285907,1171.001342,1079.209136,NaN,NaN
2,ARIMA_Sabado,1124.919889,1079.806230,1037.747329,1008.163403,1009.969519,976.432751,992.237173,1070.806841,1168.519512,...,1224.714023,1201.830184,1314.504724,1453.685771,1428.885408,1344.038075,1241.684293,1132.004180,NaN,NaN
3,PROPHET_TodosDias,1120.211184,1070.289113,1030.343744,1064.348723,1019.832758,929.901931,995.581965,980.571240,1180.191604,...,1230.694300,1199.246819,1332.347640,1457.669316,1423.699770,1359.032484,1255.448666,1164.436736,NaN,NaN
4,ARIMA_TodosDias,1125.319576,1066.075174,1018.872814,979.579753,974.135577,866.357142,883.113815,967.172032,1039.416423,...,1167.656723,1163.979767,1272.768378,1442.285391,1422.779523,1367.941672,1275.740723,1170.836205,NaN,NaN

In [74]:
dataPrueba07 = dataPrueba7.set_index('07/01/2023')
dataPrueba07

,H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,...,H17,H18,H19,H20,H21,H22,H23,H24,TOTAL,DEMANDA MAXIMA
07/01/2023,,,,,,,,,,,,,,,,,,,,,
REAL,1136.550000,1072.030000,1039.660000,1010.900000,1018.060000,972.210000,997.739000,1112.479000,1223.756000,1319.358000,...,1356.196000,1310.500000,1370.640000,1538.830000,1512.520000,1439.130000,1339.060000,1237.660000,30372.425,1540.81
PROPHET_Sabado,1058.211448,1000.510423,969.078795,950.777033,950.944046,885.658921,884.129930,975.253526,1063.502467,1107.928226,...,1114.109638,1109.464384,1191.743950,1375.092657,1343.384535,1272.285907,1171.001342,1079.209136,NaN,NaN
ARIMA_Sabado,1124.919889,1079.806230,1037.747329,1008.163403,1009.969519,976.432751,992.237173,1070.806841,1168.519512,1230.131720,...,1224.714023,1201.830184,1314.504724,1453.685771,1428.885408,1344.038075,1241.684293,1132.004180,NaN,NaN
PROPHET_TodosDias,1120.211184,1070.289113,1030.343744,1064.348723,1019.832758,929.901931,995.581965,980.571240,1180.191604,1238.252069,...,1230.694300,1199.246819,1332.347640,1457.669316,1423.699770,1359.032484,1255.448666,1164.436736,NaN,NaN
ARIMA_TodosDias,1125.319576,1066.075174,1018.872814,979.579753,974.135577,866.357142,883.113815,967.172032,1039.416423,1105.732642,...,1167.656723,1163.979767,1272.768378,1442.285391,1422.779523,1367.941672,1275.740723,1170.836205,NaN,NaN
CNDC_Predic,1123.460000,1061.160000,1039.670000,1005.830000,1015.420000,949.510000,1015.570000,1119.170000,1241.110000,1315.100000,...,1333.490000,1239.810000,1429.870000,1513.760000,1477.000000,1306.270000,1305.460000,1212.450000,NaN,NaN

In [75]:
dataPrueba_7 = dataPrueba07.drop(columns=["TOTAL","DEMANDA MAXIMA"])

In [76]:
# invertir columnas y filas
dataPrueba7inv = dataPrueba_7.transpose()
dataPrueba7inv

07/01/2023,REAL,PROPHET_Sabado,ARIMA_Sabado,PROPHET_TodosDias,ARIMA_TodosDias,CNDC_Predic
H1,1136.550,1058.211448,1124.919889,1120.211184,1125.319576,1123.46
H2,1072.030,1000.510423,1079.806230,1070.289113,1066.075174,1061.16
H3,1039.660,969.078795,1037.747329,1030.343744,1018.872814,1039.67
H4,1010.900,950.777033,1008.163403,1064.348723,979.579753,1005.83
H5,1018.060,950.944046,1009.969519,1019.832758,974.135577,1015.42
H6,972.210,885.658921,976.432751,929.901931,866.357142,949.51
H7,997.739,884.129930,992.237173,995.581965,883.113815,1015.57
H8,1112.479,975.253526,1070.806841,980.571240,967.172032,1119.17
H9,1223.756,1063.502467,1168.519512,1180.191604,1039.416423,1241.11
H10,1319.358,1107.928226,1230.131720,1238.252069,1105.732642,1315.10
H11,1383.259,1134.647716,1270.680866,1268.088115,1149.675796,1356.37
H12,1380.764,1150.651496,1256.504478,1275.695516,1163.907690,1360.24
H13,1358.871,1126.554272,1255.840185,1260.042351,1169.917454,1332.13
H14,1381.495,1112.812497,1236.281504,1258.458606,1171.744415,1341.79
H15,1394.351,1106.274650,1230.335107,1263.878687,1178.597623,1361.62
H16,1394.283,1113.892789,1214.717513,1248.023801,1180.668331,1345.18
H17,1356.196,1114.109638,1224.714023,1230.694300,1167.656723,1333.49
H18,1310.500,1109.464384,1201.830184,1199.246819,1163.979767,1239.81
H19,1370.640,1191.743950,1314.504724,1332.347640,1272.768378,1429.87
H20,1538.830,1375.092657,1453.685771,1457.669316,1442.285391,1513.76
H21,1512.520,1343.384535,1428.885408,1423.699770,1422.779523,1477.00
H22,1439.130,1272.285907,1344.038075,1359.032484,1367.941672,1306.27
H23,1339.060,1171.001342,1241.684293,1255.448666,1275.740723,1305.46
H24,1237.660,1079.209136,1132.004180,1164.436736,1170.836205,1212.45

In [77]:
# Evaluacion del modelo PROPHET que predijo usando dias especifico SABADO
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_Sabado']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_Sabado'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_Sabado']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_Sabado']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_Sabado']))

MSE of PROPHET_Lunes: 33505.084017123656
RMSE of PROPHET_Lunes: 183.04394012674567
MAE of PROPHET_Lunest: 168.8825506666667
MAPE of PROPHET_Lunes: 0.12983466408099695
R2 of PROPHET_Lunes: -0.1611030584544666

In [78]:
# Evaluacion del modelo ARIMA que predijo usando dias especifico SABADO
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_Lunes:", mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_Sabado']))
print("RMSE of ARIMA_Lunes:", np.sqrt(mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_Sabado'])))
print("MAE of ARIMA_Lunes:", mean_absolute_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_Sabado']))
print("MAPE of ARIMA_Lunes:", mean_absolute_percentage_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_Sabado']))
print("R2 of ARIMA_Lunes:", r2_score(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_Sabado']))

MSE of ARIMA_Lunes: 8675.445838543315
RMSE of ARIMA_Lunes: 93.1420734069374
MAE of ARIMA_Lunes: 75.8274285
MAPE of ARIMA_Lunes: 0.056016958374499916
R2 of ARIMA_Lunes: 0.6993564710525543

In [79]:
# Evaluacion del modelo PROPHET que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_TodosDias:", mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_TodosDias']))
print("RMSE of PROPHET_TodosDias:", np.sqrt(mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_TodosDias'])))
print("MAE of PROPHET_TodosDias:", mean_absolute_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_TodosDias']))
print("MAPE of PROPHET_TodosDias:", mean_absolute_percentage_error(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_TodosDias']))
print("R2 of PROPHET_TodosDias:", r2_score(dataPrueba7inv['REAL'],dataPrueba7inv['PROPHET_TodosDias']))

MSE of PROPHET_TodosDias: 7556.2086857886125
RMSE of PROPHET_TodosDias: 86.92645561501178
MAE of PROPHET_TodosDias: 74.35236766666668
MAPE of PROPHET_TodosDias: 0.05644201188985958
R2 of PROPHET_TodosDias: 0.738143112522702

In [80]:
# Evaluacion del modelo ARIMA que predijo usando todos los dias
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of ARIMA_TodosDias:", mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_TodosDias']))
print("RMSE of ARIMA_TodosDias:", np.sqrt(mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_TodosDias'])))
print("MAE of ARIMA_TodosDias:", mean_absolute_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_TodosDias']))
print("MAPE of ARIMA_TodosDias:", mean_absolute_percentage_error(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_TodosDias']))
print("R2 of ARIMA_TodosDias:", r2_score(dataPrueba7inv['REAL'],dataPrueba7inv['ARIMA_TodosDias']))

MSE of ARIMA_TodosDias: 20814.868984220233
RMSE of ARIMA_TodosDias: 144.2735907372525
MAE of ARIMA_TodosDias: 124.00109837500001
MAPE of ARIMA_TodosDias: 0.09567815061072965
R2 of ARIMA_TodosDias: 0.2786704242688862

In [81]:
# Evaluacion de la prediccion del CNDC
from sklearn.metrics import mean_absolute_error, mean_squared_error,mean_absolute_percentage_error,r2_score

print("MSE of PROPHET_Lunes:", mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['CNDC_Predic']))
print("RMSE of PROPHET_Lunes:", np.sqrt(mean_squared_error(dataPrueba7inv['REAL'],dataPrueba7inv['CNDC_Predic'])))
print("MAE of PROPHET_Lunest:", mean_absolute_error(dataPrueba7inv['REAL'],dataPrueba7inv['CNDC_Predic']))
print("MAPE of PROPHET_Lunes:", mean_absolute_percentage_error(dataPrueba7inv['REAL'],dataPrueba7inv['CNDC_Predic']))
print("R2 of PROPHET_Lunes:", r2_score(dataPrueba7inv['REAL'],dataPrueba7inv['CNDC_Predic']))

MSE of PROPHET_Lunes: 1615.2087471249997
RMSE of PROPHET_Lunes: 40.18965970402088
MAE of PROPHET_Lunest: 29.212208333333308
MAPE of PROPHET_Lunes: 0.021949402069685816
R2 of PROPHET_Lunes: 0.9440256942686441

In [82]:
# exportar a csv
#dataPrueba7inv.to_csv('07enero2023.csv')# exportar a csv